name: Daily Horoscope Post

# Позволяет запускать workflow вручную из интерфейса GitHub
on:
  # Ручной запуск
  workflow_dispatch:
  
  # Автоматический запуск по расписанию (9:00 по Риге = 6:00 UTC)
  schedule:
    - cron: '0 6 * * *'

jobs:
  post-horoscope:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run daily post script
        run: python main.py --daily-post
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
